name: gate

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  prek-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies (services)
        run: cd services && uv sync --dev

      - name: Install dependencies (infrastructure)
        run: cd infrastructure && uv sync --dev

      - uses: actions/checkout@v6
      - uses: j178/prek-action@v1
        env:
          SKIP: no-commit-to-branch

  infrastructure-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Ruff format check
        run: uv run ruff format . --check

      - name: Ruff lint
        run: uv run ruff check .

      - name: Ty check
        run: uv run ty check

  services-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Ruff format check
        run: uv run ruff format . --check

      - name: Ruff lint
        run: uv run ruff check .

      - name: Ty check
        run: uv run ty check

      - name: Run tests
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: ./test.sh --all
